#if !defined(__MA_CLI_FIX_H__)
#define __MA_CLI_FIX_H__

#define FID_OP_USER_CODE        "8810" //操作用户代码，填写客户代码
#define FID_OP_USERROLE         "8811" //操作用户角色，填写1，表示客户
#define FID_OP_SITE             "8812" //操作站点，填写0+网卡MAC地址
#define FID_OP_CHANNEL          "8813" //操作渠道，填写8，表示网上交易
#define FID_SESSION             "8814" //会话凭证
#define FID_FUNCID              "8815" //功能代码
#define FID_RUN_TIME            "8816" //调用时间, 格式:YYYYMMDD HH24MISSnnnnnn

#define FID_MSG_CODE            "8817" //信息代码
#define FID_MSG_LEVEL           "8818" //信息级别
#define FID_MSG_TEXT            "8819" //信息正文
#define FID_MSG_DEBUG           "8820" //调试信息
#define FID_OP_ORG              "8821" //操作机构

#define FID_ACCT_ID             "9081" //账户标识
#define FID_ACCT_TYPE           "8987" //账户类型
#define FID_ANS_FLAG            "9082" //应答标志
#define FID_AUTH_DATA           "9084" //认证数据
#define FID_AUTH_TYPE           "9083" //认证类型
#define FID_BIZ_CODE            "8980" //摘要代码
#define FID_BIZ_CONTEXT         "8981" //摘要内容
#define FID_BIZ_SN              "8982" //关联流水号
#define FID_BOND_INT            "8960" //债券利息
#define FID_BREG_STATUS         "8935" //回购状态
#define FID_BUY_UNIT            "9080" //买入最小单位
#define FID_CANCEL_STATUS       "9080" //内部撤单标志
#define FID_CLIENT_INFO         "9039" //终端信息
#define FID_COMPONET_STKBD      "8962" //成份股板块
#define FID_COMPONET_STK_CODE   "8911" //成分股代码
#define FID_COST_PRICE          "9090" //成本价格
#define FID_CUACCT_CODE         "8920" //资产账户
#define FID_CURRENCY            "15"   //货币代码
#define FID_CURRENT_PRICE       "9094" //最新价格
#define FID_CUST_CODE           "8902" //客户代码
#define FID_DIRECT              "9081" //划拨方向
#define FID_ENCRYPT_KEY         "9086" //加密因子
#define FID_ENCRYPT_TYPE        "9085" //加密方式
#define FID_FUND_AVL            "8861" //资金可用金额
#define FID_FUND_BLN            "8984" //资金余额
#define FID_FUND_FRZ            "8862" //资金冻结金额
#define FID_FUND_LOAN           "9084" //融资总金额
#define FID_FUND_PREBLN         "8860" //资金昨日余额
#define FID_FUND_STATUS         "8868" //资金状态
#define FID_FUND_TRD_BLN        "8867" //资金交易轧差金额
#define FID_FUND_TRD_FRZ        "8864" //资金交易冻结金额
#define FID_FUND_TRD_OTD        "8866" //资金交易在途金额
#define FID_FUND_TRD_UFZ        "8865" //资金交易解冻金额
#define FID_FUND_UFZ            "8863" //资金解冻金额
#define FID_FUND_VALUE          "9082" //资金资产
#define FID_HD_ID               "9015" //硬盘ID
#define FID_HIQTY_FLAG          "9082" //最大上限标志
#define FID_INT_ORG             "8911" //内部机构
#define FID_IS_WITHDRAW         "8836" //撤单标志
#define FID_IS_WITHDRAWN        "8838" //已撤单标志
#define FID_LINK_MARKET         "17"   //关联市场
#define FID_LINK_TRDACCT        "8964" //关联股东
#define FID_MARKET_VALUE        "9081" //资产总值
#define FID_MATCHED_AMT         "8504" //成交金额
#define FID_MATCHED_PRICE       "8841" //成交价格
#define FID_MATCHED_QTY         "387"  //成交数量
#define FID_MATCHED_SN          "17"   //成交编号
#define FID_MATCHED_TIME        "8840" //成交时间
#define FID_MATCHED_TYPE        "9080" //成交类型
#define FID_MKT_VAL             "8879" //市值
#define FID_OFFER_QTY           "37"   //申报数量
#define FID_OFFER_STIME         "8500" //申报时间
#define FID_ORDER_AMT           "8830" //委托金额
#define FID_ORDER_BSN           "66"   //委托批号
#define FID_ORDER_DATE          "8834" //委托日期
#define FID_ORDER_FRZ_AMT       "8831" //委托冻结金额
#define FID_ORDER_ID            "11"   //合同序号
#define FID_ORDER_PRICE         "44"   //委托价格
#define FID_ORDER_QTY           "38"   //委托数量
#define FID_ORDER_QTY_SUM       "8854" //委托数量成功累计
#define FID_ORDER_SN            "8832" //委托序号
#define FID_ORDER_STATUS        "39"   //委托状态
#define FID_ORDER_TEXT          "58"   //辅助信息
#define FID_ORDER_TIME          "8845" //委托时间
#define FID_ORDER_UFZ_AMT       "8835" //委托解冻金额
#define FID_ORDER_VALID_FLAG    "8833" //委托有效标志
#define FID_PROFIT_PRICE        "9095" //参考成本价
#define FID_PRO_INCOME          "9091" //参考盈亏
#define FID_QRY_NUM             "8992" //查询行数
#define FID_QRY_POS             "8991" //定位串
#define FID_QUERY_FLAG          "9080" //查询方向
#define FID_REMARK              "8914" //备注信息
#define FID_RESEND_FLAG         "8993" //重发标志
#define FID_SALE_UNIT           "9081" //卖出最小单位
#define FID_SECURITY_INFO       "9081" //安全信息
#define FID_SECURITY_LEVEL      "9080" //安全手段
#define FID_SERIAL_NO           "9099" //流水序号
#define FID_STKBD               "625"  //交易板块
#define FID_STKBD_LINK          "17"   //关联板块
#define FID_STKEX               "207"  //交易市场
#define FID_STKPBU              "8843" //交易单元
#define FID_STK_AVL             "8869" //证券可用数量
#define FID_STK_BCOST           "8875" //证券买入成本
#define FID_STK_BCOST_RLT       "8876" //证券买入成本（实时）
#define FID_STK_BIZ             "8842" //证券业务
#define FID_STK_BIZES           "8965" //证券业务（复数）
#define FID_STK_BIZ_ACTION      "40"   //证券业务行为
#define FID_STK_BLN             "8985" //证券余额
#define FID_STK_CAL_MKTVAL      "8955" //市值标志
#define FID_STK_CLS             "461"  //证券类别
#define FID_STK_CODE            "48"   //证券代码
#define FID_STK_CUSTODY_MODE    "8968" //托管模式
#define FID_STK_DIFF            "9096" //可申赎数量
#define FID_STK_FRZ             "8870" //证券冻结数量
#define FID_STK_ISIN            "8966" //国际编码
#define FID_STK_LOT_FLAG        "8954" //单位标志
#define FID_STK_LOT_SIZE        "561"  //每手数量
#define FID_STK_LWLMT_PRICE     "8520" //跌停价格
#define FID_STK_LWLMT_QTY       "8953" //数量下限
#define FID_STK_LWLMT_RATIO     "8951" //跌停比例
#define FID_STK_NAME            "55"   //证券名称
#define FID_STK_PLAMT           "8877" //证券盈亏金额
#define FID_STK_PLAMT_RLT       "8878" //证券盈亏金额（实时）
#define FID_STK_PREBLN          "8501" //证券昨日余额
#define FID_STK_QTY             "9093" //当前拥股数
#define FID_STK_SPREAD          "8962" //价差（价位）
#define FID_STK_STATUS          "326"  //证券状态
#define FID_STK_SUB_CLS         "8961" //证券类别子类
#define FID_STK_SUSPENDED       "8956" //停牌标志
#define FID_STK_TRD_FRZ         "8872" //证券交易冻结数量
#define FID_STK_TRD_OTD         "8874" //证券交易在途数量
#define FID_STK_TRD_UFZ         "8873" //证券交易解冻数量
#define FID_STK_TRD_UNFRZ       "9097" //已申赎数量
#define FID_STK_UFZ             "8871" //证券解冻数量
#define FID_STK_UNDL_CODE       "8964" //正股代码
#define FID_STK_UPLMT_PRICE     "8519" //涨停价格
#define FID_STK_UPLMT_QTY       "8952" //数量上限
#define FID_STK_UPLMT_RATIO     "8950" //涨停比例
#define FID_STK_VALUE           "9083" //市值
#define FID_STRATEGY_TEXT       "58"   //策略信息
#define FID_TERM_CODE           "9012" //终端特征码
#define FID_TRANS_AMT           "9083" //发生金额
#define FID_STK_TRDACCT         "448"  //证券账户
#define FID_TRDACCT_CNT         "8938" //证券账户数量
#define FID_TRDACCT_EXID        "8929" //报盘账户
#define FID_TRDACCT_NAME        "8932" //交易账户名称
#define FID_TRDACCT_SALE_LIMIT  "8939" //证券账户卖出限额
#define FID_TRDACCT_SN          "8928" //账户序号
#define FID_TRDACCT_START_NO    "8940" //证券账户起始序号
#define FID_TRDACCT_STATUS      "8933" //账户状态
#define FID_TRDACCT_SUCC_CNT    "8941" //证券账户委托成功累计
#define FID_TRD_DATE            "8844" //交易日期
#define FID_TREG_STATUS         "8934" //指定状态
#define FID_USER_MAC            "9014" //接入用户MAC
#define FID_USE_SCOPE           "9082" //使用范围
#define FID_VALUE_FLAG          "9080" //取值标志
#define FID_WITHDRAWN_QTY       "8837" //已撤单数量
#define FID_SETT_DATE           "8855" //交收日期

#define FID_SERVER_SITE_NAME    "9018" //接入站点名	
#define FID_SERVER_SITE_IP	    "9019" //接入站点IP		
#define FID_SERVER_SITE_PORT    "9020" //接入站点端口		
#define FID_SERVER_SITE_LOAD    "9021" //负载量
#define FID_SERVER_NODE_USE	    "9022" //节点用途‘n’:待机，‘s’：备机，‘a’：生产

#endif//__MA_CLI_FIX_H__
